name: Keep Render Alive

on:
  schedule:
    - cron: '*/2 * * * *' 
  workflow_dispatch:  # Enables manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -s "https://portfolio-mern-vishnu-r-2023.onrender.com/"
