name: Keep Render Alive

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -s "https://portfolio-mern-vishnu-r-2023.onrender.com/"
